select
    event_id,
    location_id,
    source,
    retrieved_at as snapshot_at,
    forecast_timezone,
    valid_at,
    date(valid_at, forecast_timezone) as local_forecast_date,
    forecast_horizon_hours,
    temperature_2m,
    apparent_temperature,
    relative_humidity_2m,
    precipitation,
    precipitation_probability,
    rain,
    showers,
    snowfall,
    weather_code,
    cloud_cover,
    pressure_msl,
    visibility,
    wind_speed_10m,
    wind_direction_10m,
    wind_gusts_10m,
    uv_index,
    is_day,
    ingested_at
from {{ ref('int_operational_hourly_forecasts') }}
